services:
  postgres:
    image: postgres:16-alpine
    container_name: securebox_postgres
    environment:
      POSTGRES_USER: securebox_user
      POSTGRES_PASSWORD: securebox_password
      POSTGRES_DB: securebox_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: